import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '~/components/footer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Footer />
      </main>
    </div>
  )
}

export default Home
